import tensorflow as tf
import time
import matplotlib.image as mpimg

# import matplotlib.pyplot as plt

class_names_translated = {
    "equus-quagga": "Plains Zebra",
    "panthera-leo": "Lion",
    "panthera-onca": "Jaguar",
    "ursus-arctos-horribilis": "Grizzly Bear",
    "megaptera-novaeangliae": "Humpback Whale",
    "panthera-tigris": "Tiger",
    "haliaeetus-leucocephalus": "Bald Eagle",
    "tyrannosaurus-rex": "T. Rex",
    "diplodocus": "Diplodocus",
    "panthera-pardus": "Leopard",
    "homo-sapiens": "Modern Humans",
    "phoebetria-fusca": "Sooty Albatross",
    "bos-taurus": "Domestic Cow",
    "gallus-gallus-domesticus": "Chicken",
    "ovis-aries": "Sheep",
    "ceratotherium-simum": "White Rhino",
    "loxodonta-africana": "African Bush Elephant",
    "tursiops-truncatus": "Common Bottlenose Dolphin",
    "orcinus-orca": "Killer Whale",
    "carcharodon-carcharias": "Great White Shark",
    "canis-lupus-familiaris": "Domestic Dog",
    "felis-catus": "Cat",
    "salmo-salar": "Salmon",
    "balaenoptera-musculus": "Blue Whale",
    "giraffa-camelopardalis": "Northern Giraffe",
    "ophiophagus-hannah": "King Cobra",
    "crotalus-atrox": "Western diamondback rattlesnake",
    "varanus-komodoensis": "Komodo Dragon",
    "pterois-mombasae": "African Lionfish",
    "spinosaurus-aegyptiacus": "Spinosaurus",
    "crocodylus-niloticus": "Crocodile",
    "falco-peregrinus": "Peregrine Falcon",
    "gorilla-gorilla": "Gorilla",
    "pongo-abelii": "Orangutan",
    "gavialis-gangeticus": "Gharial",
    "acinonyx-jubatus": "Cheetah",
    "canis-lupus": "Wolf",
    "ursus-maritimus": "Polar Bear",
    "hippopotamus-amphibius": "Hippopotamus",
    "iguana-iguana": "Green Iguana",
    "iguanodon-bernissartensis": "Iguanadon",
    "stegosaurus-stenops": "Stegosaurus",
    "triceratops-horridus": "Triceratops",
    "pteranodon-longiceps": "Pteranodon",
    "ankylosaurus-magniventris": "Ankylosaurus",
    "agalychnis-callidryas": "Tree Frog",
    "dendrobatidae": "Poison Dart Frog",
    "mellisuga-helenae": "Bee Hummingbird",
    "eudocimus-albus": "American white ibis",
    "sphyrna-mokarran": "Great hammerhead shark",
    "trilobita": "Trilobites",
    "enteroctopus-dofleini": "Giant Pacific octopus",
    "coelacanthiformes": "Coelacanth",
    "equus-caballus": "Horse",
    "odobenus-rosmarus": "Walrus",
    "physeter-macrocephalus": "Sperm Whale",
    "dugong-dugon": "Dugong",
    "eunectes-murinus": "Green Anaconda",
    "malayopython-reticulatus": "Reticulated Python",
    "rattus-rattus": "Black Rat",
    "ornithorhynchus-anatinus": "Platypus",
    "desmodus-rotundus": "Vampire Bat",
    "taurotragus-oryx": "Common Eland",
    "connochaetes-gnou": "Wildebeest",
    "puma-concolor": "Cougar",
    "formicidae": "Ant",
    "danaus-plexippus": "Monarch Butterfly",
    "papilio-glaucus": "Eastern Tiger Swallowtail",
    "heterocera": "Moth",
    "dermochelys-coriacea": "Leatherback Sea Turtle",
    "lampropeltis-triangulum": "Milk snake",
    "heloderma-suspectum": "Gila Monster",
    "macropus-giganteus": "Kangaroo",
    "ailuropoda-melanoleuca": "Giant Panda",
    "ailurus-fulgens": "Red Panda",
    "procyon-lotor": "Raccoon",
    "smilodon-populator": "Smilodon",
    "mammuthus-primigeniu": "Woolly Mammoth",
    "tapirus": "Tapir",
    "bison-bison": "American Bison",
    "alces-alces": "Moose",
    "aptenodytes-forsteri": "Emperor Penguin",
    "hydrurga-leptonyx": "Leopard Seal",
    "bradypus-variegatus": "Brown-throated Three-toed Sloth",
    "sciurus-carolinensis": "Eastern Gray Squirrel",
    "cyanocitta-cristata": "Blue Jay",
    "periplaneta-americana": "American Cockroach",
    "anas-platyrhynchos": "Mallard",
    "pavo-cristatus": "Indian Peafowl",
    "ara-macao": "Scarlet Macaw",
    "enhydra-lutris": "Sea Otter",
    "physalia-physalis": "Portuguese Man o' War",
    "codium-fragile": "Dead Man's Fingers",
    "centruroides-vittatus": "Striped Bark Scorpion",
    "lemur-catta": "Ring-tailed Lemur",
    "delphinapterus-leucas": "Beluga",
    "inia-geoffrensis": "Boto",
    "phascolarctos-cinereus": "Koala",
    "spheniscus-demersus": "African Penguin",
    "aquila-chrysaetos": "Golden Eagle",
    "branta-canadensis": "Canada Goose",
    "turdus-migratorius": "American Robin",
    "passerina-ciris": "Painted Bunting",
    "geococcyx-californianus": "Greater Roadrunner",
    "icterus-galbula": "Baltimore Oriole",
    "icterus-spurius": "Orchard Oriole",
    "crotophaga-sulcirostris": "Groove-billed Ani",
    "monodon-monoceros": "Narwhal",
    "struthio-camelus": "Common Ostrich",
    "ardea-herodias": "Great Blue Heron",
    "phoenicopterus-ruber": "American Flamingo",
    "okapia-johnstoni": "Okapi",
    "cryptoprocta-ferox": "Fossa",
    "cardinalis-cardinalis": "Northern Cardinal",
    "apis-mellifera": "Western Honey Bee",
    "telmatobufo-bullocki": "Bullock Mountains False Toad",
    "architeuthis-dux": "Giant Squid",
    "agkistrodon-contortrix": "Eastern Copperhead",
    "eidolon-helvum": "Straw-coloured Fruit Bat",
    "ceratitis-capitata": "Mediterranean Fruit Fly",
    "musca-domestica": "Common House Fly",
    "thryothorus-ludovicianus": "Carolina Wren",
    "rusa-unicolor": "Sambar",
    "bos-gaurus": "Gaur",
    "vultur-gryphus": "Andean Condor",
    "aethia-cristatella": "Crested Auklet",
    "mimus-polyglottos": "Northern Mockingbird",
    "cathartes-aura": "Turkey Vulture",
    "poecile-atricapillus": "Black-capped Chickadee",
    "mergus-serrator": "Red-breasted Merganser",
    "colaptes-auratus": "Northern Flicker",
    "circus-hudsonius": "Northern Harrier",
    "tyrannus-tyrannus": "Eastern Kingbird",
    "betta-splendens": "Siamese Fighting Fish",
    "pterois-volitans": "Common Lionfish",
    "phyllobates-terribilis": "Golden Poison Dart Frog",
    "hapalochlaena-maculosa": "Lesser Blue-ringed Octopus",
    "ovis-canadensis": "Bighorn Sheep",
    "vulpes-vulpes": "Red Fox",
    "lepus-americanus": "Snowshoe Hare",
    "dasypus-novemcinctus": "Nine-banded Armadillo",
    "martes-americana": "American Marten",
    "tarsius-pumilus": "Pygmy Tarsier",
    "melanerpes-carolinus": "Red-bellied Woodpecker",
    "icterus-gularis": "Altamira Oriole",
    "chelonia-mydas": "Green Sea Turtle",
    "chrysemys-picta": "Painted Turtle",
    "pantherophis-guttatus": "Corn Snake",
    "correlophus-ciliatus": "Crested Giant Gecko",
    "centrochelys-sulcata": "African Spurred Tortoise",
    "pantherophis-alleghaniensis": "Eastern Ratsnake",
}

class_names = [
    "acinonyx-jubatus",
    "aethia-cristatella",
    "agalychnis-callidryas",
    "agkistrodon-contortrix",
    "ailuropoda-melanoleuca",
    "ailurus-fulgens",
    "alces-alces",
    "anas-platyrhynchos",
    "ankylosaurus-magniventris",
    "apis-mellifera",
    "aptenodytes-forsteri",
    "aquila-chrysaetos",
    "ara-macao",
    "architeuthis-dux",
    "ardea-herodias",
    "balaenoptera-musculus",
    "betta-splendens",
    "bison-bison",
    "bos-gaurus",
    "bos-taurus",
    "bradypus-variegatus",
    "branta-canadensis",
    "canis-lupus",
    "canis-lupus-familiaris",
    "carcharodon-carcharias",
    "cardinalis-cardinalis",
    "cathartes-aura",
    "centrochelys-sulcata",
    "centruroides-vittatus",
    "ceratitis-capitata",
    "ceratotherium-simum",
    "chelonia-mydas",
    "chrysemys-picta",
    "circus-hudsonius",
    "codium-fragile",
    "coelacanthiformes",
    "colaptes-auratus",
    "connochaetes-gnou",
    "correlophus-ciliatus",
    "crocodylus-niloticus",
    "crotalus-atrox",
    "crotophaga-sulcirostris",
    "cryptoprocta-ferox",
    "cyanocitta-cristata",
    "danaus-plexippus",
    "dasypus-novemcinctus",
    "delphinapterus-leucas",
    "dendrobatidae",
    "dermochelys-coriacea",
    "desmodus-rotundus",
    "diplodocus",
    "dugong-dugon",
    "eidolon-helvum",
    "enhydra-lutris",
    "enteroctopus-dofleini",
    "equus-caballus",
    "equus-quagga",
    "eudocimus-albus",
    "eunectes-murinus",
    "falco-peregrinus",
    "felis-catus",
    "formicidae",
    "gallus-gallus-domesticus",
    "gavialis-gangeticus",
    "geococcyx-californianus",
    "giraffa-camelopardalis",
    "gorilla-gorilla",
    "haliaeetus-leucocephalus",
    "hapalochlaena-maculosa",
    "heloderma-suspectum",
    "heterocera",
    "hippopotamus-amphibius",
    "homo-sapiens",
    "hydrurga-leptonyx",
    "icterus-galbula",
    "icterus-gularis",
    "icterus-spurius",
    "iguana-iguana",
    "iguanodon-bernissartensis",
    "inia-geoffrensis",
    "lampropeltis-triangulum",
    "lemur-catta",
    "lepus-americanus",
    "loxodonta-africana",
    "macropus-giganteus",
    "malayopython-reticulatus",
    "mammuthus-primigeniu",
    "martes-americana",
    "megaptera-novaeangliae",
    "melanerpes-carolinus",
    "mellisuga-helenae",
    "mergus-serrator",
    "mimus-polyglottos",
    "monodon-monoceros",
    "musca-domestica",
    "odobenus-rosmarus",
    "okapia-johnstoni",
    "ophiophagus-hannah",
    "orcinus-orca",
    "ornithorhynchus-anatinus",
    "ovis-aries",
    "ovis-canadensis",
    "panthera-leo",
    "panthera-onca",
    "panthera-pardus",
    "panthera-tigris",
    "pantherophis-alleghaniensis",
    "pantherophis-guttatus",
    "papilio-glaucus",
    "passerina-ciris",
    "pavo-cristatus",
    "periplaneta-americana",
    "phascolarctos-cinereus",
    "phoebetria-fusca",
    "phoenicopterus-ruber",
    "phyllobates-terribilis",
    "physalia-physalis",
    "physeter-macrocephalus",
    "poecile-atricapillus",
    "pongo-abelii",
    "procyon-lotor",
    "pteranodon-longiceps",
    "pterois-mombasae",
    "pterois-volitans",
    "puma-concolor",
    "rattus-rattus",
    "rusa-unicolor",
    "salmo-salar",
    "sciurus-carolinensis",
    "smilodon-populator",
    "spheniscus-demersus",
    "sphyrna-mokarran",
    "spinosaurus-aegyptiacus",
    "stegosaurus-stenops",
    "struthio-camelus",
    "tapirus",
    "tarsius-pumilus",
    "taurotragus-oryx",
    "telmatobufo-bullocki",
    "thryothorus-ludovicianus",
    "triceratops-horridus",
    "trilobita",
    "turdus-migratorius",
    "tursiops-truncatus",
    "tyrannosaurus-rex",
    "tyrannus-tyrannus",
    "ursus-arctos-horribilis",
    "ursus-maritimus",
    "varanus-komodoensis",
    "vulpes-vulpes",
    "vultur-gryphus",
]

model = tf.keras.models.load_model("animals.h5", compile=False)


def guess(filepath):
    img = mpimg.imread(filepath)
    reduced_img = tf.image.resize(img, [224, 224])

    probs = model.predict(tf.expand_dims(reduced_img, axis=0))
    index = probs.argmax()
    title = class_names_translated[class_names[index]]
    return title
    # plt.imshow(img)
    # plt.title(title)
    # plt.axis(False)


print("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")

while True:
    path = input("Enter image path (or type 'close' to exit): ")
    if path == "close":
        break
    print(f"I think it is an image of '{guess(path)}'")
